export const SET_ARTICLES_SUCCESS = 'SET_ARTICLES_SUCCESS';
export const SET_ARTICLES_START = 'SET_ARTICLES_START';
export const SET_ARTICLES_FAIL = 'SET_ARTICLES_FAIL';

export const FETCH_MORE_ARTICLES_START = 'FETCH_MORE_ARTICLES_START';
export const FETCH_FILTERED_ARTICLES = 'FETCH_FILTERED_ARTICLES';

export const GET_SINGLE_ARTICLE = 'GET_SINGLE_ARTICLE';
